package org.freeplane.plugin.ai.validation.source;

import java.io.IOException;

/**
 * Prompt response data source — wraps a JSON string generated by the LLM.
 * 
 * <p>Intended to replace the direct string passing used in MindMapBufferLayer step 4.5.
 */
public final class PromptValidationSource implements ValidationSource {
    
    private final String aiResponse;
    private final String description;
    
    /**
     * @param aiResponse    the JSON string returned by the LLM
     * @param selectedModel the model name used (e.g. "ernie-4.0"), may be null
     */
    public PromptValidationSource(String aiResponse, String selectedModel) {
        this.aiResponse = aiResponse;
        this.description = (selectedModel != null) 
            ? "model=" + selectedModel 
            : "unknown-model";
    }
    
    @Override
    public String readContent() throws IOException {
        return aiResponse;
    }
    
    @Override
    public SourceType getSourceType() {
        return SourceType.PROMPT_RESPONSE;
    }
    
    @Override
    public boolean isReady() {
        return true; // Prompt response is always complete
    }
    
    @Override
    public String getDescription() {
        return description;
    }
}
