package org.freeplane.plugin.ai.validation.source;

/**
 * Enum of validation data source types, used for log tracing and fallback routing.
 */
public enum SourceType {
    /** JSON response generated by an LLM prompt */
    PROMPT_RESPONSE,

    /** Build streaming SSE chunks fully assembled */
    STREAM_ASSEMBLED,

    /** Imported from a .mm/.json file */
    FILE_IMPORT,

    /** Fetched from a remote URL (reserved) */
    URL_REMOTE
}
