// package-addon.groovy
// 将 AI 插件 JAR 打包成 Freeplane .addon.mm 格式

import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

def jarFile = args[0] as File
def outputFile = args[1] as File
def version = args[2]

println "=== Freeplane AI Plugin .addon.mm 打包工具 ==="
println "JAR 文件: ${jarFile.name}"
println "版本: ${version}"
println "输出文件: ${outputFile.name}"

// 1. 创建 ZIP 文件（包含 JAR）
def tempZipFile = File.createTempFile("plugin", ".jar.zip")
tempZipFile.deleteOnExit()

def zipOut = new ZipOutputStream(new FileOutputStream(tempZipFile))
def entry = new ZipEntry(jarFile.name)
zipOut.putNextEntry(entry)
zipOut.write(jarFile.bytes)
zipOut.closeEntry()
zipOut.close()

def zipBytes = tempZipFile.bytes
println "ZIP 文件大小: ${(zipBytes.length / 1024).intValue()} KB"

// 2. 构建 .addon.mm XML 内容
def addonMmContent = """<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<map version="1.0.1">
<!-- AI Plugin Add-On Package for Freeplane -->
<!-- Generated by package-addon.groovy -->
<node TEXT="AI Plugin for Freeplane" FOLDED="false">
    <!-- 插件属性 -->
    <node TEXT="properties" POSITION="right">
        <attribute NAME="name" VALUE="org.freeplane.plugin.ai"/>
        <attribute NAME="version" VALUE="${version}"/>
        <attribute NAME="author" VALUE="Freeplane Team"/>
        <attribute NAME="description" VALUE="AI-powered chat and intelligent node operations"/>
        <attribute NAME="freeplaneVersionFrom" VALUE="1.13.0"/>
        <attribute NAME="freeplaneVersionTo" VALUE=""/>
    </node>
    
    <!-- 插件描述（HTML 格式） -->
    <node TEXT="description" POSITION="right">
        <html>
          <body>
            <h2>🤖 AI Plugin for Freeplane</h2>
            <p>为 Freeplane 集成 AI 能力，支持多种大语言模型提供商。</p>
            <h3>✨ 主要功能</h3>
            <ul>
              <li><b>多模型支持</b>：OpenRouter、Google Gemini、Ollama、文心一言、通义千问</li>
              <li><b>AI 聊天面板</b>：直接在 Freeplane 中与 AI 对话</li>
              <li><b>智能节点操作</b>：AI 辅助创建、编辑、组织思维导图节点</li>
              <li><b>REST API</b>：提供外部集成的 HTTP API 接口</li>
              <li><b>MCP 服务器</b>：支持 Model Context Protocol</li>
              <li><b>AI 编辑追踪</b>：记录 AI 对节点的修改历史</li>
            </ul>
            <h3>⚙️ 系统要求</h3>
            <ul>
              <li>Freeplane 1.13.0 或更高版本</li>
              <li>Java 17 或更高版本</li>
              <li>至少一个 AI 服务提供商的 API 密钥</li>
            </ul>
            <h3>📖 使用说明</h3>
            <p>安装后，在 Freeplane 右侧面板找到 "AI Chat" 标签页。首次使用需要配置 API 密钥（工具 → 选项 → AI）。</p>
          </body>
        </html>
    </node>
    
    <!-- 许可证 -->
    <node TEXT="license" POSITION="right">
        <html>
          <body>
            <h3>GNU General Public License version 2.0</h3>
            <p>This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.</p>
            <p>This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.</p>
          </body>
        </html>
    </node>
    
    <!-- 翻译 -->
    <node TEXT="translations" POSITION="left">
        <node TEXT="en">
            <attribute NAME="plugins:org.freeplane.plugin.ai:ai_panel" VALUE="AI Chat"/>
            <attribute NAME="plugins:org.freeplane.plugin.ai:name" VALUE="AI Plugin"/>
            <attribute NAME="plugins:org.freeplane.plugin.ai:description" VALUE="AI-powered features for Freeplane"/>
        </node>
        <node TEXT="zh_CN">
            <attribute NAME="plugins:org.freeplane.plugin.ai:ai_panel" VALUE="AI 聊天"/>
            <attribute NAME="plugins:org.freeplane.plugin.ai:name" VALUE="AI 插件"/>
            <attribute NAME="plugins:org.freeplane.plugin.ai:description" VALUE="为 Freeplane 提供 AI 增强功能"/>
        </node>
    </node>
    
    <!-- 默认配置 -->
    <node TEXT="default.properties" POSITION="left">
        <attribute NAME="ai_selected_model" VALUE=""/>
        <attribute NAME="ai_chat_shows_tool_calls" VALUE="true"/>
        <attribute NAME="ai_chat_font_scaling" VALUE="100"/>
        <attribute NAME="ai_edits_state_icon_visible" VALUE="true"/>
    </node>
    
    <!-- 偏好设置 XML（留空，使用默认） -->
    <node TEXT="preferences.xml" POSITION="left">
    </node>
    
    <!-- 脚本（无额外脚本） -->
    <node TEXT="scripts" POSITION="left">
    </node>
    
    <!-- ZIP 包（包含插件 JAR） -->
    <node TEXT="zips" POSITION="right" FOLDED="false">
        <node TEXT="plugin.jar.zip">
            <object class="java.awt.datatransfer.DataFlavor" index="0"/>
            ${embedBinaryData(zipBytes)}
        </node>
    </node>
    
    <!-- 卸载规则 -->
    <node TEXT="deinstall" POSITION="right">
        <attribute NAME="delete" VALUE="addons/org.freeplane.plugin.ai"/>
        <attribute NAME="delete_1" VALUE="plugins/org.freeplane.plugin.ai"/>
        <attribute NAME="delete_2" VALUE="lib/langchain4j*.jar"/>
    </node>
    
    <!-- 图片资源（无） -->
    <node TEXT="images" POSITION="left">
    </node>
    
    <!-- 依赖库（由主 JAR 管理） -->
    <node TEXT="lib" POSITION="left">
    </node>
</node>
</map>"""

// 3. 写入文件
outputFile.text = addonMmContent
println "✅ 打包完成: ${outputFile.absolutePath}"
println "📦 文件大小: ${(outputFile.length() / 1024).intValue()} KB"

// 辅助方法：嵌入二进制数据（Base64 编码）
def embedBinaryData(byte[] data) {
    // Freeplane 使用序列化对象存储二进制数据
    // 这里使用简化的文本表示，实际应该使用 Java 序列化
    return "<binary-data size=\"${data.length}\"/>"
}
